apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: default
spec:
  containers:
  - name: minio
    image: docker.io/alexmerenstein/minio:0.0.1
    command: ["/bin/bash", "-c", "minio server /data"]
    env:
      - name: MINIO_ACCESS_KEY
        value: minioadmin
      - name: MINIO_SECRET_KEY
        value: minioadmin
    volumeMounts:
    - mountPath: /data
      name: localvolume
  volumes:
  - name: localvolume
    hostPath:
      path: /tmp/data
      type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: default
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc-external
  namespace: default
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30002
  selector:
    app: minio
  sessionAffinity: None
  type: NodePort
